name: build
on: [pull_request, push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - loader: fabric
            java: '21'
            build_cmd: './gradlew build'
            artifact_path: 'build/libs/'
          - loader: forge
            java: '17'
            build_cmd: './gradlew -p forge build'
            artifact_path: 'forge/build/libs/'
          - loader: neoforge
            java: '21'
            build_cmd: './gradlew -p neoforge build'
            artifact_path: 'neoforge/build/libs/'
          - loader: quilt
            java: '17'
            build_cmd: './gradlew -p quilt build'
            artifact_path: 'quilt/build/libs/'
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: validate gradle wrapper
        uses: gradle/actions/wrapper-validation@v4

      - name: setup jdk
        uses: actions/setup-java@v4
        with:
          java-version: '${{ matrix.java }}'
          distribution: 'microsoft'

      - name: make gradle wrapper executable
        run: chmod +x ./gradlew

      - name: build ${{ matrix.loader }}
        run: ${{ matrix.build_cmd }}

      - name: capture ${{ matrix.loader }} artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Artifacts-${{ matrix.loader }}
          path: ${{ matrix.artifact_path }}
